version: "3"
services:
  web:
    build:
      context: web
    ports:
      - "8000:80"
    environment:
      ENVIRONMENT: dev
      API_URL: localhost:5000
    volumes:
      - ./web/app:/code/app
    links:
      - api
  api:
    build:
      context: api
    ports:
      - "5000:80"
    environment:
      ENVIRONMENT: dev
      WEB_URL: localhost:8000
    volumes:
      - ./api/app:/code/app
      - ./db:/code/app/db
