version: "3"
services:
  web:
    build:
      context: web
    ports:
      - "8000:80"
    environment:
      API_URL: http://api:80
      ENVIRONMENT: dev
      FLASK_DEBUG: 1
      SECRET_KEY: "0cX78ltAhxMlwTDAQQYdlXvapcJMWA=="
    volumes:
      - ./web/app:/code/app
    links:
      - api
  api:
    build:
      context: api
    ports:
      - "5000:80"
    environment:
      ENVIRONMENT: dev
      POSTGRES_DB: example
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      WEB_URL: web:8000
    volumes:
      - ./api/app:/code/app
    links:
      - db
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: example
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - ./db:/var/lib/postgresql/data
