version: "3"
services:
  web:
    build:
      context: web
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 1024M
    environment:
      API_URL: http://api:80
      ENVIRONMENT: dev
      FLASK_DEBUG: 1
      SECRET_KEY: "0cX78ltAhxMlwTDAQQYdlXvapcJMWA=="
    links:
      - api
    ports:
      - "8000:80"
    volumes:
      - ./web/app:/code/app
  api:
    build:
      context: api
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "2048M"
    environment:
      ENVIRONMENT: dev
      POSTGRES_DB: example
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      WEB_URL: web:8000
    links:
      - db
    ports:
      - "5000:80"
    volumes:
      - ./api/app:/code/app
  db:
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: "2048M"
    environment:
      POSTGRES_DB: example
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
